from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph
from pydantic import BaseModel, Field

from src.service.file_format_service import soup_html_to_text
from src.service.graph.core.reflect_answer_graph import run_reflect_agent
from src.service.thirdparty.news.finhub_news_service import fetch_company_news
from src.service.thirdparty.stock_price_change_service import \
  get_price_change_for_tickers
from src.tools.tools import report_rephrase_retriever_search
from typing_extensions import TypedDict
import os
from src.llm import llm_provider
from src.usecase.report_uc import save_text_report

LOGIC = """
     1.	Correction (temporary fall, likely rebound)
    •	The stock price has fallen by 1–3%.
    •	No significant negative company-specific news is present.
    •	News is related to market-wide factors (sector sentiment, macroeconomic data, analyst comments, general volatility).
    •	The company’s fundamentals, guidance, and core business remain unchanged.
    •	Examples:
    •	A broad market sell-off that also affects peers.
    •	Temporary negative sentiment or rumors.
    •	A small dip without any meaningful news.
    2.	Structural Issue (risk of further decline)
    •	News or filings reveal changes that could reduce the company’s future income or strategic position.
    •	Examples of structural risk:
    •	Downgraded revenue, profit, or earnings guidance.
    •	Declining sales of the company’s main product.
    •	Regulatory penalties or lawsuits that impact financial results.
    •	Loss of major contracts, partnerships, or customers.
    •	Negative updates in official reports (10-K, 10-Q, earnings call).
    •	These indicate a real degradation in company value, not just market sentiment.
    3.	Decision Rule
    •	If the fall appears to be a correction, the stock is considered a potential buying opportunity.
    •	If the fall is due to a structural issue, the stock should be considered risky and avoided.
    •	Always explicitly state whether the fall is a Correction or Structural Issue, explain why, and provide a clear verdict.
    
    """
REASON_PROMPT = f"""
You're the hedge fond manager. Usually there are only stock shares in your portfolio.
You have a very specific strategy of trading share prices on stock markets.
You try to find the stock that fall down on some percents and try to understand if this fall is temporary or it is a structural issue that may drive the stock price down even more.
If it's a temporary fall - you buy the stock shares, if it's structural issue - you avoid buying this stock shares.

Here is the logic you use to make decision:
{LOGIC}

You are provided with following information:
1. Ticker symbol. Ticker symbol of the company
2. Share price change. Percentage change of stock price for the last day
3. Analytical summary. Analytical summary of the stock price fall that was generated by another agent using all the available information about the company including recent news and risk factors from the latest financial report.

Based on provide information and having your strategy and logic of criteria for classification of the fall - 
you need to provide two things:

1. Summary verdict in a short clear form. THing step by step explaining your reasoning, why you made particular decision to buy or not.
2. Verdict in a form of mark with range from -5 to 5 where:
-5 = absolutely should not buy the stock share. Companys sells fall. 
-4 = should not buy. F.e. Company lost some major contracts, partnerships, or customers.
-3 = better not to buy. F.e. Regulatory penalties or lawsuits that impact financial results. Competitors pressure
-2 = better not to buy. F.e. Downgraded revenue, profit, or earnings guidance. Margin fall. 
-1 = preferable not to buy. F.e. Major pressure on the whole sector this company related to
0 = absolutely neutral. Don't have enough information to make decision. Use it when information is not relevant or not enough. Or share price move is not explainable in expert summary. Or news ara mixed.
1 = preferable to buy the stock share. F.e. Share price fall is related to some temporary market wide issue.
2 = better to buy the stock share. F.e. Share price fall is related to some temporary market wide issue or rumors and company fundamentals are strong.
3 = better to buy the stock share. F.e. Share price fall is related to someone speech about the future of the whole industry bit nothing is change for the company itself.
4 = should buy the stock share. F.e. Share price dropped but there are only positive news related this company. F.e. Rating agency raised the rating of this company.
5 = must buy the stock share. F.e. Share price dropped but there are only positive news related this company. F.e. Rating agency raised the rating of this company or they updated it' revenue forecast.
"""



REFLECT_QUESTION = "Does provided news can explain the share price move ? If yes - explain why the share price change using provided information and provided recent news?"

TASK_ROLE_PROMPT = """You are stock market expert. You specialize on reasoning between the recent news related to the stock market and share prices movement.Taking in to account provided stock
You are always provided with following information:
1. Ticker symbol. Ticker symbol of the company
2. Share price change. Percentage change of stock price for the last day
3. Recent news. Recent news someone found that somehow may be related to the company
4. Company risk factors. Risk factors that company wrote itself in the latest annual financial report that may impact the share price.
5. Suggestion of expert on what to focus on if exist. (May not be provided)

Using this information you need to provide answer on user's question.
Think step by step with follow up reasoning. If you don't have enough information to make a decision, say that you don't have enough information.
Style of the answer must be short and concise. Onlu relevant information must be provided in answer.
"""


MARK_ROLE_PROMPT = """
You are a strict evaluator of stock market analysis.
You are provided with user's question and the answer to this question provided by the stock market expert.

Your task is to assess the quality of the analysis based on its accuracy, relevance, and depth of reasoning.
Provide a mark from 1 to 10, where 10 indicates a perfect analysis that thoroughly addresses the question with clear, logical 
reasoning and accurate use of data. A mark of 1 indicates a poor analysis that fails to address the question, lacks logical reasoning, 
or contains significant inaccuracies. Justify your mark with specific feedback on what was done well and what could be improved.

Imagine as you as a reader read this answer. You need to understand if you can trust logic this answer or not.
Example of mark graduation:
1-3: Answer is largely irrelevant or incorrect, with little to no logical reasoning.
4-5: Answer addresses the question but lacks depth or contains some inaccuracies. Answer very abstract and not related to the question.
6-7: Answer is generally accurate and relevant, with some logical reasoning, but could be more thorough or clearer. It's not answering the users question directly or does it only partly.
8-9: Answer is accurate, relevant, and demonstrates strong logical reasoning, with minor areas for improvement.
10: Answer is perfect in all aspects - accuracy, relevance, and logical reasoning.

If you see that answer is telling that there is not enough information to make decision but in reality there is enough information - give mark 1-3 and explain why you think so.
If you see that answer is telling that there is not enough information to make decision and in reality there is not enough information - give mark 8-10 and explain why you think so.
"""

REVIEW_ROLE_PROMPT = """
You are an expert reviewer tasked with providing constructive feedback on stock market analyses. You a proficient of giving feedback about share price movements and revising the overall reasoning quality.
You are provided with user's question and the answer to this question provided by the stock market expert. Also you are provided with the data that expert used to make the analysis.
If someone call you it means that quality of the analysis was not good enough and you need to provide feedback on how to improve it.

Focus on the following aspects when providing your review in following priority:
1. Reasoning Quality: Evaluate the logical coherence and depth of the analysis. Did the analyst follow a clear line of reasoning? Were assumptions and conclusions well-supported by evidence? What if expert halucinated? What if his reasoning not following the overall logic of stock market. Check if the expert made right logical steps to come to the conclusion.
2. Relevance: Assess whether the analysis directly addresses the user's question. Did the analyst stay on topic and avoid unnecessary tangents? Did they consider all relevant factors that could impact the stock price movement?
3. Clarity and Communication: Consider the clarity of the writing and the effectiveness of communication. If the answer style short and concise? If the answer is easy to read and understand? If the expert used professional language?

Taking in to account all these factors, provide clear and actionable feedback that the analyst can use to improve future rework.
Form answer not like the feedback to already existed answer but like it would do the absolutely new expert that know to context about previous answer.
"""


news_mock = [
  {
    "headline": "Apple shares climb after unveiling next-gen iPhone 16 and AI-powered features",
    "id": "0AAPL",
    "relevance_score": 0,
    "summary": "Apple stock rallied after announcing new devices and AI upgrades at its September event.",
    "text": "Apple Inc. (AAPL) unveiled the iPhone 16 lineup, featuring new AI-powered camera tools and improved battery life. The company also introduced expanded AI integration across iOS and macOS. Investors responded positively, sending Apple shares up 3%.",
    "url": "https://finnhub.io/api/news?id=apple_event_iphone16_ai",
  },
  {
    "headline": "Tim Cook emphasizes AI investments during Apple’s quarterly earnings call",
    "id": "1AAPL",
    "relevance_score": 0,
    "summary": "Apple CEO highlighted AI as a core growth driver while reporting better-than-expected quarterly results.",
    "text": "On the company’s latest earnings call, CEO Tim Cook said Apple is ‘all-in on artificial intelligence.’ Revenue topped Wall Street expectations, driven by strong iPhone sales in Asia and growth in Apple Services.",
    "url": "https://finnhub.io/api/news?id=aapl_earnings_ai_focus",
  },
  {
    "headline": "Apple faces antitrust scrutiny in the U.S. over App Store practices",
    "id": "2AAPL",
    "relevance_score": 0,
    "summary": "Regulators are investigating Apple’s App Store policies and their impact on competition.",
    "text": "The U.S. Department of Justice expanded its probe into Apple’s App Store fees and restrictions on third-party apps. This comes amid growing global scrutiny of big tech firms and their control over digital ecosystems.",
    "url": "https://finnhub.io/api/news?id=aapl_antitrust_probe",
  },
  {
    "headline": "Apple invests $5B in new data centers to support AI cloud services",
    "id": "3AAPL",
    "relevance_score": 0,
    "summary": "Apple is expanding its data infrastructure to compete with Amazon, Google, and Microsoft in AI-driven cloud services.",
    "text": "Apple announced a $5 billion investment in new U.S. and European data centers, aimed at scaling its upcoming AI services. Analysts say this signals Apple’s deeper commitment to competing in enterprise cloud and AI.",
    "url": "https://finnhub.io/api/news?id=aapl_cloud_investment",
  },
  {
    "headline": "Apple stock dips as iPad and Mac sales disappoint despite strong iPhone demand",
    "id": "4AAPL",
    "relevance_score": 0,
    "summary": "While iPhone revenue grew, weaker demand for Macs and iPads weighed on Apple’s latest quarterly report.",
    "text": "Apple reported mixed quarterly results: iPhone sales exceeded expectations, but Mac and iPad revenue declined sharply. The stock slipped 2% in after-hours trading as investors reacted to weaker-than-expected performance in non-iPhone segments.",
    "url": "https://finnhub.io/api/news?id=aapl_qreport_mixed",
  },
]

COLLECT_FALL_TICKERS_NODE = "COLLECT_FALL_TICKERS"
GENERATE_VERDICT_NODE = "GENERATE_VERDICT"
GENERATE_MSG_NODE = "GENERATE_MSG"



class FallenCompanyVerdict(BaseModel):
  """Structured output model for the verdict on a fallen company's stock price. Include 3 sentences summary and final verdict."""
  summary_text: str  = Field(description="Using provided information, give a concise summary verdict around 7 sentences explaining why you are thinking so. And main answer - if this fall is temporary or long term. Think step by step explaining why exactly you think so based on provided information. If you don't have enough information to make a decision, say that you don't have enough information.")
  verdict_type: str =  Field(description='Only three values are allowed: "Correction", "Structural Issue", "Not Enough Information". If you think that the fall is temporary and likely to rebound, choose "Correction". If you believe the fall is due to a structural issue that could lead to further decline, select "Structural Issue". If the information provided is insufficient to make a clear determination, select "Not Enough Information".')

class NegativeFiveToFiveMark(BaseModel):
  """Schema for making marks in range from -5 to 5 and explaining your reasoning."""
  reasoning: str = Field(description="Provide a brief explanation for your rating thinking step by step explaining your thoughts why you giving this mark.")
  mark : int = Field(description="Provide a score from -5 to 5 based on provided data to mark if I should buy the stock share or not where -5 means I absolutely should not to do it and 0 is full neutral mark and 5 - absolutely should buy.")



class CompanyFallExplanation(TypedDict):
  ticker: str
  change: float | None
  report_risk_factors: str | None
  news: list | None
  summary: str | None
  verdict: str | None
  reasoning: str | None
  verdict_type: str | None
  finished = bool | None
  reflection_state: map | None

class GraphFallExplainState(TypedDict):
  """Graph reflection state."""
  tickers_to_check: list[str] | None
  company_fall_explanation: list[CompanyFallExplanation] | None
  answer: str | None

def collect_fall_change_tickers(state: GraphFallExplainState) -> GraphFallExplainState:
  ticker_to_change_map = get_price_change_for_tickers(state["tickers_to_check"])
  for ticker in state["tickers_to_check"]:
    change = ticker_to_change_map[ticker]
    if change < -1.0:
      company_fall_explanation: CompanyFallExplanation = {
        "ticker": ticker,
        "change": change}

      state['company_fall_explanation'] = state.get('company_fall_explanation', []) + [company_fall_explanation]

  for fall_company in state['company_fall_explanation']:
    news = fetch_company_news(fall_company['ticker'])
    # news = news_mock
    fall_company['news'] = news
  print("Tickers with significant fall:", state['company_fall_explanation'])

  for fall_company in state['company_fall_explanation']:
    if not fall_company.get('news') or len(fall_company['news']) == 0:
      fall_company['verdict'] = "No news found to explain the stock price fall."
      fall_company['finished'] = True

  for fall_company in state['company_fall_explanation']:
    if 'finished' not in fall_company:
      query = f"List the risk factors mentioned in the latest financial report. Provide a concise summary of each risk factor for share stock prise. With given score of impact for each risk  factor by yourself using reasonong. "
      response = report_rephrase_retriever_search(fall_company['ticker'], query)['answer']
      fall_company['report_risk_factors'] = response

  return state



def generate_verdict_node(state: GraphFallExplainState) -> GraphFallExplainState:
  print("VERDICT NODE")

  for idx, company_explanation in enumerate(state['company_fall_explanation']):
    if company_explanation.get('finished'):
      continue



    data = ""
    data += f"Ticker: {company_explanation['ticker']}\n"
    data += f"Share price change: {company_explanation['change']}%\n"
    data += f"Report Risk Factors: {company_explanation.get('report_risk_factors', 'No data')}\n"
    if 'news' in company_explanation and company_explanation['news'] and len(company_explanation['news']) > 0:
      news_summaries = [f"- {news_item['headline']}\n{news_item['text']}" for news_item in company_explanation['news']]
      data += "Recent News that can be relevant and can affect the price:\n" + "\n".join(news_summaries) + "\n"
    else:
      data += "No relevant news found.\n"

    reflect_state = run_reflect_agent(
    question = REFLECT_QUESTION,
    task_data_prompt = data,
    task_role_prompt = TASK_ROLE_PROMPT,
    mark_role_prompt = MARK_ROLE_PROMPT,
    review_role_prompt = REVIEW_ROLE_PROMPT,

    max_iterations = 3,
    accepted_mark = 9
    )

    llm = llm_provider.get_llm().with_structured_output(NegativeFiveToFiveMark)
    prompt = ChatPromptTemplate.from_messages([
        ("system", REASON_PROMPT),
        ("human", """
          Ticker: {ticker}
          Change: {change}%
          Analytical summary: {analytical_summary}

          Please provide a verdict in a mark form if I should but the stock share right now or not.
          """)
      ])

    chain = prompt | llm

    response: NegativeFiveToFiveMark = chain.invoke({
      "ticker": company_explanation['ticker'],
      "change": company_explanation['change'],
      "analytical_summary": reflect_state['final_answer']
    })

    state['company_fall_explanation'][idx]['verdict_type'] = response.mark
    state['company_fall_explanation'][idx]['verdict'] = response.reasoning
    state['company_fall_explanation'][idx]['reasoning'] = reflect_state['final_answer']
    state['company_fall_explanation'][idx]['reflection_state'] = reflect_state
    state['company_fall_explanation'][idx]['finished'] = True

  return state


def form_response_node(state: GraphFallExplainState) -> GraphFallExplainState:
  print("FORM RESPONSE NODE")

  answer = ""
  for idx, company_explanation in enumerate(state['company_fall_explanation']):
    if not company_explanation.get('finished'):
      continue

    answer += "\n\n"
    answer += company_explanation['ticker'] + "\n"
    answer += str(company_explanation['change']) + "\n"

    if 'news' in company_explanation and company_explanation['news'] and len(company_explanation['news']) > 0:
      news_summaries = [f"- {news_item['headline']}\n{news_item['url']}" for news_item in company_explanation['news']]
      answer += "News:\n" + "\n".join(news_summaries) + "\n"
    else:
      answer += "No relevant news found.\n"
      continue

    if 'reasoning' in company_explanation and company_explanation['reasoning']:
      answer += "\nReasoning:\n" + company_explanation['reasoning'] + "\n"

    if 'verdict' in company_explanation and company_explanation['verdict']:
      answer += "\n\nVerdict:\n" + company_explanation['verdict'] + "\n"
      answer += "\nFinal Verdict:\n" + str(company_explanation['verdict_type']) + "\n"

    state['answer'] = answer

  return state

graph = StateGraph(GraphFallExplainState)
graph.add_node(COLLECT_FALL_TICKERS_NODE, collect_fall_change_tickers)
graph.add_node(GENERATE_VERDICT_NODE, generate_verdict_node)
graph.add_node(GENERATE_MSG_NODE, form_response_node)

graph.set_entry_point(COLLECT_FALL_TICKERS_NODE)
graph.set_finish_point(GENERATE_MSG_NODE)
graph.add_edge(COLLECT_FALL_TICKERS_NODE, GENERATE_VERDICT_NODE)
graph.add_edge(GENERATE_VERDICT_NODE, GENERATE_MSG_NODE)


app = graph.compile(debug=True)


def run_company_fall_explanation_graph(tickers: list[str]) -> GraphFallExplainState:
  initial_state = GraphFallExplainState(
      tickers_to_check=tickers,
      company_fall_explanation=[],
      answer=None
  )

  final_state = app.invoke(initial_state)
  print("Final State:", final_state)
  return final_state['answer']

if __name__ == "__main__":
  # with open("/Users/ibahr/Downloads/synthetic_report.pdf", "rb") as f:
  # with open("/Users/ibahr/Desktop/reports/UBER.html", "rb") as f:
  #   pdf_content = f.read()
  #   report = soup_html_to_text(pdf_content)
  #
  #   metadata = {
  #     "ticker": "UBER",
  #     "date": "2025-07-17"
  #   }
  #
  # # save_report(pdf_content, metadata)
  # save_text_report(report, metadata)
  tickers = []
  folder = "/Users/ibahr/Desktop/reports"
  for filename in os.listdir(folder):
    print(filename)
    ticker = filename.split('.')[0]
    tickers.append(ticker)
    with open(folder + '/' + filename, "rb") as f:
      report = f.read()
    report = soup_html_to_text(report)
    metadata = {
      "ticker": ticker,
      "date": "2025-07-17"
    }
    # save_report(pdf_content, metadata)
    save_text_report(report, metadata)
    tickers = ['ORCL',
               'SOFI',
               'OKTA',
               'FICO',
               'IONQ',
               'PGY',
               'MU',
               'AAPL',
               'UBER',
               'TOST',
               'RKLB',
               'AMZN',
               'RGTI']

  initial_state = GraphFallExplainState(
      tickers_to_check=tickers,
      # tickers_to_check=['UBER'],
      company_fall_explanation=[]
  )


  final_state = app.invoke(initial_state)
  print("Final State:", final_state)
  print(final_state['answer'])
